In [991]:
import numpy as np

e = 0.0001
A = np.array([[864, 307, 269, -369, 275],[307, 537, 195, -280, 192],[269, 195, 412, -289, -4],\
              [-369, -280, -289, 375, -174],[275, 192, -4, -174, 377]])

In [992]:
y = np.array([1,1,1,1,1])
x = y/y.max()
y = np.dot(A, x)
I_k = np.average(y/x)
I = 0
x = y/y.max()
k=1
while abs(I_k - I) >=e:
    k+=1
    I = I_k
    y = np.dot(A, x)
    I_k = y/x
    x = y/y.max()
    print('\n')
    print(k, 'ітерація: y=', y)
    print('y(i)k/y(i)k-1=',  I_k)
    I_k = np.average(I_k)
print("\nнайбільше власне число", I_k)
print('відповідний власний вектор', x)



2 ітерація: y= [1535.53566122 1019.1872214   741.48885587 -983.43239227  690.73551263]
y(i)k/y(i)k-1= [1535.53566122 1442.50893796 1711.91080617 1796.0651289  1395.99099099]


3 ітерація: y= [ 1557.69264734  1023.28173856   780.66765836 -1012.83905409
   681.5307836 ]
y(i)k/y(i)k-1= [1557.69264734 1541.70457405 1616.67032415 1581.45135227 1515.07314059]


4 ітерація: y= [ 1560.73929073  1023.56069924   789.74417835 -1017.73699148
   677.20933511]
y(i)k/y(i)k-1= [1560.73929073 1558.11729579 1575.80333542 1565.2254148  1547.81563416]


5 ітерація: y= [ 1561.39503716  1023.73902674   792.0765291  -1018.89640837
   675.93745132]
y(i)k/y(i)k-1= [1561.39503716 1561.01120692 1565.34862064 1562.51730165 1557.80802722]


6 ітерація: y= [ 1561.58902482  1023.84214365   792.71240651 -1019.22386385
   675.60712781]
y(i)k/y(i)k-1= [1561.58902482 1561.5523099  1562.64852187 1561.89684222 1560.63199987]


7 ітерація: y= [ 1561.65138205  1023.88605839   792.88943866 -1019.3210888
   675.52515195]
y(

In [993]:
def get_max(B):
    matr = abs(B)
    for i in range(len(matr)):
        matr[i, i] = 0
        max_el = matr.max()
        ind = np.unravel_index(np.argmax(matr, axis=None), matr.shape)
    return max_el, ind

In [994]:
def summ(B):
    summ=0
    for i in range(len(B)):
        for j in range(len(B[0])):
            if i!=j:
                summ+=B[i,j]**2
    return summ

In [995]:
max_el, ind = get_max(A)
A_new = A.copy()
i = ind[1] 
j = ind[0]
k=1
vect = np.eye(A_new.shape[0])
while  summ(A_new) >= e:
    T = (A_new[i,i] - A_new[j,j])/(2*A_new[i,j])
    if T==0:
        c = np.sqrt(2)/2 
        s = np.sqrt(2)/2
    elif T<0:
        t = 1/(T - np.sqrt(T**2 + 1))
        c = 1/(np.sqrt(1+ t**2))
        s = c*t
    else:
        t = 1/(T + np.sqrt(T**2 + 1))
        c = 1/(np.sqrt(1+ t**2))
        s = c*t
    k+=1
    print('\n\nk =', k)
    print('c, s =', c, s)
    print('c^2 + s^2 = ', c**2 + s**2)
    T_matr = np.eye(A_new.shape[0])
    T_matr[i,i] = c
    T_matr[j,j] = c
    T_matr[i,j] = -s
    T_matr[j,i] = s
    vect = np.dot(vect, T_matr)
    B = np.dot(np.dot(T_matr.T, A_new), T_matr)
    max_el, ind = get_max(B)
    A_new = B
    print('A =', A_new)
    print('max_element =', max_el)
    print('index = ',ind)
    sum_d =0
    sum_nd = 0
    for i in range(len(B)):
        for j in range(len(B)):
            if j==i:
                sum_d += B[i,j]**2
            else:
                sum_nd+= B[i,j]**2
    print('pow sum of diag elem =', sum_d)
    print('pow sum of non-diag elem =', sum_nd)
    print('full sum =', sum_nd + sum_d)
    i = ind[1] 
    j = ind[0]
for i in range(5):
    print('\nвласне число',A_new[i,i])
    print('власний вектор',vect[:,i]/np.max(vect[:,i]))



k = 2
c, s = 0.8810085113667264 0.4731004152390743
c^2 + s^2 =  0.9999999999999999
A = [[ 1.06215252e+03  4.02937729e+02  3.73717310e+02  8.77649009e-15
   3.24596813e+02]
 [ 4.02937729e+02  5.37000000e+02  1.95000000e+02 -1.01440556e+02
   1.92000000e+02]
 [ 3.73717310e+02  1.95000000e+02  4.12000000e+02 -1.27347448e+02
  -4.00000000e+00]
 [ 1.12949670e-14 -1.01440556e+02 -1.27347448e+02  1.76847484e+02
  -2.31928668e+01]
 [ 3.24596813e+02  1.92000000e+02 -4.00000000e+00 -2.31928668e+01
   3.77000000e+02]]
max_element = 402.9377292565258
index =  (0, 1)
pow sum of diag elem = 1759685.0
pow sum of non-diag elem = 1018673.9999999999
full sum = 2778359.0


k = 3
c, s = 0.8791935340264122 -0.47646482527690115
c^2 + s^2 =  1.0
A = [[ 1.28051815e+03  2.00494906e-14  4.21480483e+02 -4.83328566e+01
   3.76864666e+02]
 [ 1.90902795e-14  3.18634365e+02 -6.62041347e+00 -8.91858807e+01
   1.41461948e+01]
 [ 4.21480483e+02 -6.62041347e+00  4.12000000e+02 -1.27347448e+02
  -4.00000000e+00]
 [-4.8

In [996]:
A = np.array([[-888, 92, 138,671,148],[-61, -493, -974,739,98],[-231, -208, -833,804,621],\
              [7, 42, 359,-477,29],[-866, 58, 976,-247,-592]])
A_new = A.copy()

In [997]:
for i in range(A_new.shape[0]):
    s1 = np.sign(-A_new[i,i])*np.sqrt(np.sum(A_new[i:,i]**2))
    m1 = 1/np.sqrt(2*s1*(s1-A_new[i,i]))
    W1 = np.zeros(shape = (A_new.shape[0],1))
    W1[i] = A_new[i,i] - s1
    for j in range(i+1, A_new.shape[0]):
        W1[j] = A_new[j,i]
    W1*=m1
    P1 = np.eye(A_new.shape[0]) - 2*np.dot(W1,W1.T)
    Q = np.dot(Q, P1)
    A_new = np.dot(P1, A_new)
R = A_new
A_new = np.dot(R,Q)
print('k =0')
print('Q =',Q)
print('R =',R)
k=1
while np.all(np.abs(np.abs(Q) - np.eye(5))) >= e:
    Q = np.eye(A_new.shape[0])  
    k+=1
    for i in range(A_new.shape[0]):
        s1 = np.sign(-A_new[i,i])*np.sqrt(np.sum(A_new[i:,i]**2))
        m1 = 1/np.sqrt(2*s1*(s1-A_new[i,i]))
        W1 = np.zeros(shape = (A_new.shape[0],1))
        W1[i] = A_new[i,i] - s1
        for j in range(i+1, A_new.shape[0]):
            W1[j] = A_new[j,i]
        W1*=m1
        P1 = np.eye(A_new.shape[0]) - 2*np.dot(W1,W1.T)
        Q = np.dot(Q, P1)
        A_new = np.dot(P1, A_new)
    print('k =', k)
    print('Q =',Q)
    print('R =',A_new)
    R = A_new
    A_new = np.dot(R,Q)
for i in range(5):
    print('\n\nвласне число', R[i,i])

k =0
Q = [[ 0.70298613 -0.11395853  0.48272763 -0.13163662 -0.49241221]
 [ 0.04829027  0.90668554 -0.21797186 -0.18857714 -0.30416496]
 [ 0.18287135  0.39514311  0.49643651  0.55254962  0.50858598]
 [-0.00554156 -0.07735371 -0.30876513  0.8010901  -0.50685741]
 [ 0.68556977 -0.05303886 -0.61455447  0.00735003  0.38658731]]
R = [[ 1.26318288e+03 -4.23604536e+01 -5.64771743e+02 -4.87726684e+02
   1.83680449e+02]
 [ 2.75248224e-15  5.45995048e+02  1.30752837e+03 -9.61267553e+02
  -3.46529174e+02]
 [-8.55181066e-14 -2.83767215e-15  8.45262355e+02 -8.61039950e+02
  -7.13231512e+02]
 [ 9.62303028e-15 -1.48289253e-14  2.32352858e-14  1.67372568e+02
  -3.24050836e+02]
 [ 6.71809067e-14 -3.68126763e-15  6.83605672e-15  2.81501081e-15
   3.04120002e+01]]
k = 2
Q = [[-0.91569403 -0.033707   -0.38419243 -0.11197595  0.01502795]
 [-0.03339287 -0.96451591  0.21016586 -0.15463383  0.02264214]
 [ 0.33121267 -0.24785909 -0.85755224  0.30190549 -0.04817965]
 [ 0.22416203  0.08421533 -0.2683186  -0.93211