In [2]:
import numpy as np 
   
x = np.arange(0, 1.2, 0.2) 
y = np.flip(np.arange(0, 1.2, 0.2)) 
arr = np.zeros((6, 6)) 
n = len(arr)
eps = 0.001
f = np.full((n-2, n-2), False) 

for i in range(0, n-1):
    arr[0][i] = 50 -10*i
    
arr[:,i+1] = 0
arr[:, 0] = 50*y**2 
arr[i+1] = 60*x*(1-x**2)

for i in range(1, n-1): 
        arr[i] = np.array([arr[i][0] + (arr[i][-1] - arr[i][0])/(n-1)*k for k in range(n)]) 
#print(arr)
k = 0 
while not f.all(): 
    k += 1 
    for i in range(1, n-1): 
        for j in range(1, n-1): 
            new_x = 1/4*(arr[i-1][j] + arr[i+1][j] + arr[i][j-1] + arr[i][j+1]) 
            if abs(new_x - arr[i][j]) <= eps: 
                f[i-1][j-1] = True 
            arr[i][j] = new_x 
    print(k) 
    print(np.round(arr, 4), '\n') 

[[50.   40.   30.   20.   10.    0.  ]
 [32.   25.6  19.2  12.8   6.4   0.  ]
 [18.   14.4  10.8   7.2   3.6   0.  ]
 [ 8.    6.4   4.8   3.2   1.6   0.  ]
 [ 2.    1.6   1.2   0.8   0.4   0.  ]
 [ 0.   11.52 20.16 23.04 17.28  0.  ]]
1
[[50.     40.     30.     20.     10.      0.    ]
 [32.     26.4    20.     13.4     6.75    0.    ]
 [18.     15.4    11.85    8.0125  4.0906  0.    ]
 [ 8.      7.45    5.925   4.0844  2.1438  0.    ]
 [ 2.      5.5425  8.1069  8.9078  7.0829  0.    ]
 [ 0.     11.52   20.16   23.04   17.28    0.    ]] 

2
[[50.     40.     30.     20.     10.      0.    ]
 [32.     26.85   20.525  13.8219  6.9781  0.    ]
 [18.     16.0375 12.625   8.6555  4.4443  0.    ]
 [ 8.      8.8763  8.4231  7.0325  4.6399  0.    ]
 [ 2.      7.6258 11.2792 12.1087  8.5071  0.    ]
 [ 0.     11.52   20.16   23.04   17.28    0.    ]] 

3
[[50.     40.     30.     20.     10.      0.    ]
 [32.     27.1406 20.8969 14.1326  7.1442  0.    ]
 [18.     16.6605 13.659   9.8171  5.40

In [11]:
n = 7 
arr = np.zeros((n, n)) 
x = np.arange(0, 0.7, 0.1) 
t = np.arange(0, 0.011, 0.01/6) 

arr[0] = np.cos(2*x +0.19) 
arr[:,0] = 0.982
arr[:,n-1] = 0.1798

for i in range(1, n): 
    for j in range(1, n-1): 
        arr[i][j] = 1/6*(arr[i-1][j-1] + 4*arr[i-1][j] + arr[i-1][j+1]) 
print(np.round(arr, 4))

[[0.982  0.9249 0.8309 0.7038 0.5487 0.3717 0.1798]
 [0.982  0.9188 0.8254 0.6992 0.545  0.3692 0.1798]
 [0.982  0.9137 0.8199 0.6945 0.5414 0.3669 0.1798]
 [0.982  0.9095 0.8147 0.6899 0.5379 0.3648 0.1798]
 [0.982  0.9058 0.8097 0.6854 0.5344 0.3628 0.1798]
 [0.982  0.9025 0.805  0.6809 0.5309 0.3609 0.1798]
 [0.982  0.8995 0.8005 0.6766 0.5276 0.3591 0.1798]]
